-- Migration: Add ads_payment table + link records via FK
-- Run in Supabase Dashboard → SQL Editor → paste ALL, click RUN

-- Step 1: Drop existing ads_payment table (if exists from earlier attempts)
drop table if exists ads_payment;

-- Step 2: Create ads_payment table (no record_ids array — records point to it)
create table ads_payment (
  id bigint generated by default as identity primary key,
  total_amount numeric default 0 not null,
  paid_date date default current_date not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Step 3: Enable RLS on ads_payment
alter table ads_payment enable row level security;

-- Step 4: Create policies for ads_payment
create policy "Enable read access for authenticated users" on ads_payment
  for select using (auth.uid() is not null);

create policy "Enable insert access for authenticated users" on ads_payment
  for insert with check (auth.uid() is not null);

-- Step 5: Add payment_id FK to records table (nullable — NULL means unpaid)
alter table records add column if not exists payment_id bigint references ads_payment(id);

-- Step 6: Create index on payment_id for faster lookups
create index if not exists records_payment_id_idx on records(payment_id);

-- Step 7: Create policy update on records for payment_id (needed for marking paid)
create policy "Enable update of payment_id for user records" on records
  for update using (auth.uid() = user_id);

-- Verify
select 'ads_payment + records linked via payment_id' as status;
