-- Migration: Add receipts_payment table + link receipt_records via FK
-- Run in Supabase Dashboard → SQL Editor → paste ALL, click RUN

-- Step 1: Drop existing receipts_payment table (if exists from earlier attempts)
drop table if exists receipts_payment;

-- Step 2: Create receipts_payment table
create table receipts_payment (
  id bigint generated by default as identity primary key,
  total_amount numeric default 0 not null,
  paid_date date default current_date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()))
;

-- Step 3: Enable RLS on receipts_payment
alter table receipts_payment enable row level security;

-- Step 4: Create policies for receipts_payment
create policy "authenticated can read receipts payments" on receipts_payment
  for select using (auth.uid() is not null);

create policy "authenticated can insert receipts payments" on receipts_payment
  for insert with check (auth.uid() is not null);

-- Step 5: Add payment_id FK to receipt_records table (nullable — NULL means unpaid)
alter table receipt_records add column if not exists payment_id bigint references receipts_payment(id);

-- Step 6: Create index on payment_id for faster lookups
create index if not exists receipt_records_payment_id_idx on receipt_records(payment_id);

-- Step 7: Update policy on receipt_records for payment_id updates
create policy "Enable update of payment_id for user receipts" on receipt_records
  for update using (auth.uid() = user_id);

-- Verify
select 'receipts_payment + receipt_records linked via payment_id' as status;
